name: flutter_application_1
description: Student Dashboard

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '^3.10.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  google_fonts: ^6.1.0
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  image_picker: ^1.0.7
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  
  # ✅ Chỉ khai báo assets tồn tại
  assets:
    - assets/images/
